package com.hermes.agent.data.chat

import android.content.Context
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import java.io.File
import javax.inject.Inject
import javax.inject.Singleton

/** What a reply's model thought before answering, and roughly how long it took. */
@Serializable
data class StoredReasoning(val text: String, val millis: Long) {
    /** `Thought for 6s`, or `Thought for a moment` when it was too quick to say. */
    val label: String
        get() = when {
            millis < 1_000 -> "Thought for a moment"
            millis < 60_000 -> "Thought for ${millis / 1000}s"
            else -> "Thought for ${millis / 60_000}m ${(millis % 60_000) / 1000}s"
        }
}

/**
 * Keeps each reply's reasoning in a small file named after the message, next to the chat database.
 *
 * It is a file rather than a database column on purpose: the message table is shared with the
 * other apps built on the same engine, and a new column would need a schema migration in each of
 * them. Files under the app's private folder are carried by the full backup, so the reasoning
 * survives a reinstall together with the chats.
 */
@Singleton
class ReasoningStore @Inject constructor(@ApplicationContext private val context: Context) {

    private val dir get() = File(context.filesDir, "reasoning")
    private val json = Json { ignoreUnknownKeys = true }

    suspend fun save(messageId: String, text: String, millis: Long) {
        if (text.isBlank()) return
        withContext(Dispatchers.IO) {
            runCatching {
                dir.mkdirs()
                file(messageId).writeText(json.encodeToString(StoredReasoning.serializer(), StoredReasoning(text.trim(), millis)))
            }
        }
    }

    /** The saved reasoning for each of [messageIds] that has any. */
    suspend fun load(messageIds: Collection<String>): Map<String, StoredReasoning> = withContext(Dispatchers.IO) {
        messageIds.mapNotNull { id ->
            val f = file(id)
            if (!f.isFile) return@mapNotNull null
            runCatching { id to json.decodeFromString(StoredReasoning.serializer(), f.readText()) }.getOrNull()
        }.toMap()
    }

    // Message ids are generated by the app, but the name still never reaches the filesystem unchecked.
    private fun file(messageId: String) = File(dir, messageId.filter { it.isLetterOrDigit() || it == '-' || it == '_' } + ".json")
}
