package com.sassybutler.alarm

import android.content.ContentValues
import android.content.Context
import android.content.pm.PackageManager
import android.net.Uri
import android.provider.CalendarContract
import android.content.ContentUris
import androidx.core.content.ContextCompat
import java.util.Calendar
import java.util.TimeZone

object CalendarSyncManager {

    // We map our Alarm ID to a Calendar Event ID stored in SharedPreferences
    private const val PREFS_NAME = "calendar_sync_prefs"

    data class TodayEvent(val title: String, val startMillis: Long, val allDay: Boolean)

    fun hasReadPermission(context: Context): Boolean =
        ContextCompat.checkSelfPermission(context, android.Manifest.permission.READ_CALENDAR) ==
            PackageManager.PERMISSION_GRANTED

    /** Today's events from every visible calendar, earliest first. Empty if permission is missing. */
    fun todayEvents(context: Context): List<TodayEvent> {
        if (!hasReadPermission(context)) return emptyList()

        val dayStart = Calendar.getInstance().apply {
            set(Calendar.HOUR_OF_DAY, 0); set(Calendar.MINUTE, 0)
            set(Calendar.SECOND, 0); set(Calendar.MILLISECOND, 0)
        }.timeInMillis
        val dayEnd = dayStart + 24 * 60 * 60 * 1000L

        val projection = arrayOf(
            CalendarContract.Instances.TITLE,
            CalendarContract.Instances.BEGIN,
            CalendarContract.Instances.ALL_DAY,
        )
        val uri = CalendarContract.Instances.CONTENT_URI.buildUpon().apply {
            ContentUris.appendId(this, dayStart)
            ContentUris.appendId(this, dayEnd)
        }.build()

        val events = mutableListOf<TodayEvent>()
        try {
            context.contentResolver.query(uri, projection, null, null, CalendarContract.Instances.BEGIN)
                ?.use { cursor ->
                    while (cursor.moveToNext()) {
                        events += TodayEvent(
                            title = cursor.getString(0) ?: "Untitled event",
                            startMillis = cursor.getLong(1),
                            allDay = cursor.getInt(2) != 0,
                        )
                    }
                }
        } catch (e: SecurityException) {
            // Permission not granted
        }
        return events
    }

    fun syncAlarmToCalendar(context: Context, alarm: Alarm) {
        if (!alarm.enabled) {
            removeAlarmFromCalendar(context, alarm.id)
            return
        }

        val cal = Calendar.getInstance().apply {
            set(Calendar.HOUR_OF_DAY, alarm.hour)
            set(Calendar.MINUTE, alarm.minute)
            set(Calendar.SECOND, 0)
            set(Calendar.MILLISECOND, 0)
            // If the time has already passed today, schedule for tomorrow
            if (before(Calendar.getInstance())) {
                add(Calendar.DAY_OF_MONTH, 1)
            }
        }

        val values = ContentValues().apply {
            val title = if (alarm.label.isNotBlank()) "Jeeves: ${alarm.label}" else "Jeeves Wake-up"
            put(CalendarContract.Events.DTSTART, cal.timeInMillis)
            put(CalendarContract.Events.DTEND, cal.timeInMillis + 1000 * 60 * 15) // 15 mins event
            put(CalendarContract.Events.TITLE, title)
            put(CalendarContract.Events.DESCRIPTION, "Automated event generated by Jeeves.")
            put(CalendarContract.Events.CALENDAR_ID, getDefaultCalendarId(context))
            put(CalendarContract.Events.EVENT_TIMEZONE, TimeZone.getDefault().id)
            put(CalendarContract.Events.HAS_ALARM, 1)
        }

        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        val existingEventId = prefs.getLong("event_${alarm.id}", -1L)

        try {
            if (existingEventId != -1L) {
                // Update
                val updateUri = ContentUris.withAppendedId(CalendarContract.Events.CONTENT_URI, existingEventId)
                context.contentResolver.update(updateUri, values, null, null)
            } else {
                // Insert
                val uri: Uri? = context.contentResolver.insert(CalendarContract.Events.CONTENT_URI, values)
                uri?.lastPathSegment?.toLongOrNull()?.let { newEventId ->
                    prefs.edit().putLong("event_${alarm.id}", newEventId).apply()
                }
            }
        } catch (e: SecurityException) {
            // Permission not granted
        }
    }

    fun removeAlarmFromCalendar(context: Context, alarmId: Int) {
        val prefs = context.getSharedPreferences(PREFS_NAME, Context.MODE_PRIVATE)
        val existingEventId = prefs.getLong("event_$alarmId", -1L)
        if (existingEventId != -1L) {
            try {
                val deleteUri = ContentUris.withAppendedId(CalendarContract.Events.CONTENT_URI, existingEventId)
                context.contentResolver.delete(deleteUri, null, null)
            } catch (e: SecurityException) {
                // Permission not granted
            }
            prefs.edit().remove("event_$alarmId").apply()
        }
    }

    private fun getDefaultCalendarId(context: Context): Long {
        val projection = arrayOf(CalendarContract.Calendars._ID)
        val selection = "${CalendarContract.Calendars.VISIBLE} = 1 AND ${CalendarContract.Calendars.IS_PRIMARY} = 1"
        try {
            context.contentResolver.query(
                CalendarContract.Calendars.CONTENT_URI,
                projection,
                selection,
                null,
                null
            )?.use { cursor ->
                if (cursor.moveToFirst()) {
                    return cursor.getLong(0)
                }
            }
            // Fallback to the first visible calendar
            context.contentResolver.query(
                CalendarContract.Calendars.CONTENT_URI,
                projection,
                "${CalendarContract.Calendars.VISIBLE} = 1",
                null,
                null
            )?.use { cursor ->
                if (cursor.moveToFirst()) {
                    return cursor.getLong(0)
                }
            }
        } catch (e: SecurityException) {
            // Permission not granted
        }
        return 1L // Failsafe default
    }
}
